version: '3.8'

services:
  be:
    image: ${DOCKER_USERNAME}/be_inner_peace
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    restart: unless-stopped
    tty: true
