version: '3.8'

services:
  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    restart: unless-stopped
    tty: true
