/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * This API exposes endpoints to manage demo.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vuthase172485@fpt.edu.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CaloricBreakdown
 */
export interface CaloricBreakdown {
    /**
     * 
     * @type {number}
     * @memberof CaloricBreakdown
     */
    percentProtein?: number;
    /**
     * 
     * @type {number}
     * @memberof CaloricBreakdown
     */
    percentFat?: number;
    /**
     * 
     * @type {number}
     * @memberof CaloricBreakdown
     */
    percentCarbs?: number;
}

/**
 * Check if a given object implements the CaloricBreakdown interface.
 */
export function instanceOfCaloricBreakdown(value: object): value is CaloricBreakdown {
    return true;
}

export function CaloricBreakdownFromJSON(json: any): CaloricBreakdown {
    return CaloricBreakdownFromJSONTyped(json, false);
}

export function CaloricBreakdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaloricBreakdown {
    if (json == null) {
        return json;
    }
    return {
        
        'percentProtein': json['percentProtein'] == null ? undefined : json['percentProtein'],
        'percentFat': json['percentFat'] == null ? undefined : json['percentFat'],
        'percentCarbs': json['percentCarbs'] == null ? undefined : json['percentCarbs'],
    };
}

export function CaloricBreakdownToJSON(value?: CaloricBreakdown | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'percentProtein': value['percentProtein'],
        'percentFat': value['percentFat'],
        'percentCarbs': value['percentCarbs'],
    };
}

