/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * This API exposes endpoints to manage demo.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vuthase172485@fpt.edu.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Equipment
 */
export interface Equipment {
    /**
     * 
     * @type {string}
     * @memberof Equipment
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Equipment
     */
    localizedName?: string;
    /**
     * 
     * @type {string}
     * @memberof Equipment
     */
    image?: string;
}

/**
 * Check if a given object implements the Equipment interface.
 */
export function instanceOfEquipment(value: object): value is Equipment {
    return true;
}

export function EquipmentFromJSON(json: any): Equipment {
    return EquipmentFromJSONTyped(json, false);
}

export function EquipmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Equipment {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'localizedName': json['localizedName'] == null ? undefined : json['localizedName'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function EquipmentToJSON(value?: Equipment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'localizedName': value['localizedName'],
        'image': value['image'],
    };
}

