/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * This API exposes endpoints to manage demo.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vuthase172485@fpt.edu.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Flavonoid
 */
export interface Flavonoid {
    /**
     * 
     * @type {string}
     * @memberof Flavonoid
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Flavonoid
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof Flavonoid
     */
    unit?: string;
}

/**
 * Check if a given object implements the Flavonoid interface.
 */
export function instanceOfFlavonoid(value: object): value is Flavonoid {
    return true;
}

export function FlavonoidFromJSON(json: any): Flavonoid {
    return FlavonoidFromJSONTyped(json, false);
}

export function FlavonoidFromJSONTyped(json: any, ignoreDiscriminator: boolean): Flavonoid {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'unit': json['unit'] == null ? undefined : json['unit'],
    };
}

export function FlavonoidToJSON(value?: Flavonoid | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'amount': value['amount'],
        'unit': value['unit'],
    };
}

