/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * This API exposes endpoints to manage demo.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vuthase172485@fpt.edu.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstructionDuration
 */
export interface InstructionDuration {
    /**
     * 
     * @type {number}
     * @memberof InstructionDuration
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof InstructionDuration
     */
    unit?: string;
}

/**
 * Check if a given object implements the InstructionDuration interface.
 */
export function instanceOfInstructionDuration(value: object): value is InstructionDuration {
    return true;
}

export function InstructionDurationFromJSON(json: any): InstructionDuration {
    return InstructionDurationFromJSONTyped(json, false);
}

export function InstructionDurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstructionDuration {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'unit': json['unit'] == null ? undefined : json['unit'],
    };
}

export function InstructionDurationToJSON(value?: InstructionDuration | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'number': value['number'],
        'unit': value['unit'],
    };
}

