/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * This API exposes endpoints to manage demo.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vuthase172485@fpt.edu.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface LessonEntity
 */
export interface LessonEntity {
  /**
   *
   * @type {Date}
   * @memberof LessonEntity
   */
  createdAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof LessonEntity
   */
  updatedAt?: Date;
  /**
   *
   * @type {number}
   * @memberof LessonEntity
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof LessonEntity
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof LessonEntity
   */
  duration?: number;
  /**
   *
   * @type {string}
   * @memberof LessonEntity
   */
  description?: string;
  /**
   *
   * @type {boolean}
   * @memberof LessonEntity
   */
  isVip?: boolean;
  /**
   *
   * @type {string}
   * @memberof LessonEntity
   */
  imgUrl?: string;
  /**
   *
   * @type {string}
   * @memberof LessonEntity
   */
  videoUrl?: string;
}

/**
 * Check if a given object implements the LessonEntity interface.
 */
export function instanceOfLessonEntity(value: object): value is LessonEntity {
  return true;
}

export function LessonEntityFromJSON(json: any): LessonEntity {
  return LessonEntityFromJSONTyped(json, false);
}

export function LessonEntityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LessonEntity {
  console.log(json);
  if (json == null) {
    return json;
  }
  return {
    createdAt:
      json["createdAt"] == null ? undefined : new Date(json["createdAt"]),
    updatedAt:
      json["updatedAt"] == null ? undefined : new Date(json["updatedAt"]),
    id: json["id"] == null ? undefined : json["id"],
    name: json["name"] == null ? undefined : json["name"],
    duration: json["duration"] == null ? undefined : json["duration"],
    description: json["description"] == null ? undefined : json["description"],
    isVip: json["isVip"] == null ? undefined : json["isVip"],
    imgUrl: json["imgUrl"] == null ? undefined : json["imgUrl"],
    videoUrl: json["videoUrl"] == null ? undefined : json["videoUrl"],
  };
}

export function LessonEntityToJSON(value?: LessonEntity | null): any {
  if (value == null) {
    return value;
  }
  return {
    createdAt:
      value["createdAt"] == null ? undefined : value["createdAt"].toISOString(),
    updatedAt:
      value["updatedAt"] == null ? undefined : value["updatedAt"].toISOString(),
    id: value["id"],
    name: value["name"],
    duration: value["duration"],
    description: value["description"],
    isVip: value["isVip"],
    imgUrl: value["imgUrl"],
    videoUrl: value["videoUrl"],
  };
}
