/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * This API exposes endpoints to manage demo.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vuthase172485@fpt.edu.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Nutrient
 */
export interface Nutrient {
    /**
     * 
     * @type {string}
     * @memberof Nutrient
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Nutrient
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof Nutrient
     */
    unit?: string;
    /**
     * 
     * @type {number}
     * @memberof Nutrient
     */
    percentOfDailyNeeds?: number;
}

/**
 * Check if a given object implements the Nutrient interface.
 */
export function instanceOfNutrient(value: object): value is Nutrient {
    return true;
}

export function NutrientFromJSON(json: any): Nutrient {
    return NutrientFromJSONTyped(json, false);
}

export function NutrientFromJSONTyped(json: any, ignoreDiscriminator: boolean): Nutrient {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'percentOfDailyNeeds': json['percentOfDailyNeeds'] == null ? undefined : json['percentOfDailyNeeds'],
    };
}

export function NutrientToJSON(value?: Nutrient | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'amount': value['amount'],
        'unit': value['unit'],
        'percentOfDailyNeeds': value['percentOfDailyNeeds'],
    };
}

