/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * This API exposes endpoints to manage demo.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vuthase172485@fpt.edu.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidateOtpRequest
 */
export interface ValidateOtpRequest {
    /**
     * 
     * @type {string}
     * @memberof ValidateOtpRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidateOtpRequest
     */
    otp?: string;
}

/**
 * Check if a given object implements the ValidateOtpRequest interface.
 */
export function instanceOfValidateOtpRequest(value: object): value is ValidateOtpRequest {
    return true;
}

export function ValidateOtpRequestFromJSON(json: any): ValidateOtpRequest {
    return ValidateOtpRequestFromJSONTyped(json, false);
}

export function ValidateOtpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidateOtpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'otp': json['otp'] == null ? undefined : json['otp'],
    };
}

export function ValidateOtpRequestToJSON(value?: ValidateOtpRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'otp': value['otp'],
    };
}

