/* tslint:disable */
/* eslint-disable */
/**
 * Backend API
 * This API exposes endpoints to manage demo.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: vuthase172485@fpt.edu.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WeightPerServing
 */
export interface WeightPerServing {
    /**
     * 
     * @type {number}
     * @memberof WeightPerServing
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof WeightPerServing
     */
    unit?: string;
}

/**
 * Check if a given object implements the WeightPerServing interface.
 */
export function instanceOfWeightPerServing(value: object): value is WeightPerServing {
    return true;
}

export function WeightPerServingFromJSON(json: any): WeightPerServing {
    return WeightPerServingFromJSONTyped(json, false);
}

export function WeightPerServingFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeightPerServing {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'unit': json['unit'] == null ? undefined : json['unit'],
    };
}

export function WeightPerServingToJSON(value?: WeightPerServing | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'unit': value['unit'],
    };
}

