spring:
  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:thaodb}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:26122020@Nvy}
    driver-class-name: com.mysql.cj.jdbc.Driver

ngrok:
  enabled: true
  authToken: 2j3eywVGY3RUtXA2g9uq4UobMyS_8771WqFo19DEmNnS7Zj6u