spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_ID}
            clientSecret: ${GOOGLE_SECRET}
            redirectUri: "${BASE_URL}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: ${FACEBOOK_ID}
            clientSecret: ${FACEBOOK_SECRET}
            redirectUri: "${BASE_URL}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v18.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v18.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v18.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,picture.width(250).height(250)
