server:
  port: ${SERVER_PORT:8080}

spring:

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:thaodb}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:03102003@Phuc}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_ID}
            clientSecret: ${GOOGLE_SECRET}
            redirectUri: "${BASE_URL}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: ${FACEBOOK_ID}
            clientSecret: ${FACEBOOK_SECRET}
            redirectUri: "${BASE_URL}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v18.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v18.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v18.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,picture.width(250).height(250)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
app:
  api:
    version:
      v1: /api/v1
  mail:
    host: smtp.gmail.com
    port: 587
    username: vuthase172485@fpt.edu.vn
    password: qapy rgmx gsnm gyen
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  openapi:
    dev-url: http://localhost:${SERVER_PORT:8080}
    prod-url: http://159.223.36.234:8080
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    refreshTokenExpirationMsec: 864000000  # 10 ngày
    accessTokenExpirationMsec: 864000000
    #accessTokenExpirationMsec: 900000 # 15 phút
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:3001,http://159.223.36.234:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
